### ISSUE TITLE
[FEATURE] Add Death Rates for 2022

### ISSUE THREAD

**Issue by GregorSchroeder** [SANDAG/Cohort-Component-Model#54]
**Is your feature request related to a problem? Please describe.**
Currently, there are no death rates for 2022 if that year is chosen as a launch year (or increment year between base and later launch) despite it being September 2024.

**Describe the solution you'd like**
Add a mapping for 2022 death rates to the `rates_map.yml` and update this project's Wikipedia section on Death Rates to reflect this addition.

**Describe alternatives you've considered**
No alternative.

**Additional context**
See the note in the [Death Rates Wikipedia](https://github.com/SANDAG/Cohort-Component-Model/wiki/Death-Rates) section for how to decide/download/map the appropriate death rates for 2022:

*Note there is preference given to using actual race/ethnicity category data when available (in 2018 the ucd-icd10-expanded becomes available), 5-year rates, and never including both 2020 and 2021 datasets together due to the outsize impact of COVID-19; in that respective order.*

**Comment by GregorSchroeder** [comment]
1. The following mapping uses rates for the actual race/ethnicity categories first and foremost. This means that `Native Hawaiian or Other Pacific Islander alone` and `Two or More Races` must use the [newer CDC Underlying Cause of Death product](https://wonder.cdc.gov/ucd-icd10-expanded.html) as the old product does not split out those race/ethnicity categories with years 2018-2019 and 2021-2022.
2. Then, 5-years of rates are prioritized noting that 2020 and 2021 datasets must never be used together due to the impact of the COVID-19 pandemic on death rates. This means that the `Hispanic`, `White alone`, `Black or African American alone`, `American Indian or Alaska Native alone`, and `Asian alone` must use the [older CDC Underlying Cause of Death product](https://wonder.cdc.gov/ucd-icd10.html) with years 2016-2020.

 ```yaml
 "2022":
    Hispanic: "Hispanic or Latino; ucd-icd10; 2016-2020; Five Counties.txt"
    White alone: "Non-Hispanic White; ucd-icd10; 2016-2020; California (06).txt"
    Black or African American alone: "Non-Hispanic Black or African American; ucd-icd10;
      2016-2020; Arizona (04), California (06), Oregon (41), Washington (53).txt"
    American Indian or Alaska Native alone: "Non-Hispanic American Indian or Alaska
      Native; ucd-icd10; 2016-2020; National.txt"
    Asian alone: "Non-Hispanic Asian or Pacific Islander; ucd-icd10; 2016-2020; Arizona
      (04), California (06), Oregon (41), Washington (53).txt"
    Native Hawaiian or Other Pacific Islander alone: "Non-Hispanic Native Hawaiian
      or Other Pacific Islander; ucd-icd10-expanded; 2018-2019, 2021-2022; National.txt"
    Two or More Races: "Non-Hispanic More than one race; ucd-icd10-expanded; 2018-2019,
      2021-2022; National.txt"
```
